ALTER TABLE project ALTER COLUMN description DROP NOT NULL;
ALTER TABLE project ALTER COLUMN location_lat DROP NOT NULL;
ALTER TABLE project ALTER COLUMN location_long DROP NOT NULL;
ALTER TABLE project ALTER COLUMN roi_from DROP NOT NULL;
ALTER TABLE project ALTER COLUMN roi_to DROP NOT NULL;
ALTER TABLE project ALTER COLUMN start_date DROP NOT NULL;
ALTER TABLE project ALTER COLUMN end_date DROP NOT NULL;
ALTER TABLE project ALTER COLUMN expected_funding DROP NOT NULL;
ALTER TABLE project ALTER COLUMN currency DROP NOT NULL;
ALTER TABLE project ALTER COLUMN min_per_user DROP NOT NULL;
ALTER TABLE project ALTER COLUMN max_per_user DROP NOT NULL;
ALTER TABLE project ALTER COLUMN active DROP NOT NULL;

